language: node_js
node_js:
  - stable
deploy:
  provider: npm
  email: yadickson@gmail.com
  api_key: EZjFKZWy8Y3w+4ePEWW+N/o1dj1c4RwSzZmArVCqwzR6ymKtfgHtvoPFgP+PJG5v2S2Fj0lYsWOBJuyZJET5Ys9irHIoFJnKo0zd9HarowGp6d1JtsGp4i0lglMbcSBqyJcAUrvz7U8Ok2akIVkBbCF5bXkZ1XY/fNp06SWNlIt1+6Mb0VpGMkRcfpY7QhRHDAKPkdIWJKFDSkwaLKNO9CPss0lhswCQO6ur1hhuKGwyzQJDLHG9R162cwa7XI7qSH+HfDn7wLSFGueoCU9ZV9PH/hRu0jceYLqVCJ6NLItDXChFebKMG/RNku5l933XL5QNSM4hSXEDHdBqnw1XqVb2kxMqS3dZjXi2Zyc0VWwJq2fTVJpctR8BcTe5Yavo8KKo5avsMcTFHo/S7+O/lpS8UjxjtKRYga2umCSD/vubiUgmnEjLarvsSsMYH9oDbMqqE+XyL1lBTjoGuer/pbdLgO90FhO4IwDY3O1xhRa3tb6tHQIX9TrGlIuY/uFAew7rzZ1sF+43f3zoMCOKYZ1qX3rXMoDac7zZQLVGirXFD9TtnxbRXZXTY3lpKHA1tIsQaK1Us8lQcte3Cpa8u7TxCuwFW9Lut2FxgDBCFJ3IuaI+JBrDsGrSuhCaky59VnoB8FI1sUmLkXPsphcMhoWI+xcfJ3SJQAL+VwqbM5Q=
  on:
    tags: true

