language: node_js
node_js:
  - stable
deploy:
  provider: npm
  email: yadickson@gmail.com
  api_key: mAvltqULaU6J5kyZOlnwEGFNSeyBnR/hxvHg0lN2IVR3KAIP4Tw1etCm7rV3xV10M7WAVkPRTYSVDqe70Ls7j1wVc1Y9EpABHAAYaK2fdRmUjhi9++ZnVrFl/BLwjomVzpe0wbbH0swVp9l8hE1xLcf5FY3cYc17z0SkXbIjlZD8kKeQ0r6JKDYh6MTdixpnJpL0PrGWxPxB6yJP+jAZ/9+bmjD4l7myWwFRiKV8g/uCwTbgl90fak3p4gw+cU41mIQIfrIOWLnZmeQe3kRBypTcSY2EzKxxOEghmI1T93oqF9bw5cCdGuZf3bBodB5K7ypwc3TPy+aLeItsD3KYcxAV/qO1fZhp3z70F9LIDHwRzbsXkk6iRp0WW8xJqiWNZKi2dJJw3mrfya0r1KaFgAKj1BD+tvWADPGd0oIEdPjaF7xf3fttCrloZmT2LNaz4QK+UpQ/fDvhasC/aRCF3vgpkTnMaxKFZdvy4kEzO2iYDX8TnUzG3ebs6K2oy2MYPfujfok61ja61ZFk+mwAAIx5GnUa7I2BoC30QPZ8dvh0A7s/fpYhQKHwxulsp5b/YrDqvJ5Q/g1BQ2kWyI4qtoGRRNpDnZgLOns7pEEPTmxxWIJPATVqA9SlcjqQIL+b7dejNIrrRQydqm2LCw9yMPYrP3hz7vtCOzP9wwLgo0s=
  on:
    tags: true

