language: node_js
node_js:
- stable
after_success: npm run coveralls
deploy:
  provider: npm
  email: yadickson@gmail.com
  api_key:
    secure: B0VLp/nX4KndJva1hTBlFrcrSCgA6+s35TgqpCNbUqYvAsbO8+wYGNqPRrVW5o9oMQKSu9fYfJRGNzimhf07+KQtRKHLY0XlKTt1OxFCHLn8NUs4rVwCkksZGAkiY/gkEMDJFPEMq+R/xtmgabxvXDJ/t0kFJ2SAK7B2Nujh5r8CkAKrDUqiFsbm3sC2rTjW+IqvpBGxCDWbUeRqAHwniBNh2QqBbbh0+IhnKIAWJYSGBEO92G3dSZ8cUaU1chltYpFIiUYDKrvUCFB/lunsAuJmcrHalQi0AvPcjxruGiIABz4Z4l5ir+A5+SYbQs92C1fovHYEj5zEfr4789hZGyOk+fhuTzM+EZEAKw6aTqV7sLyjkYCMoJrBYVJey1xIppija1uy8qrIS+YKDNcROf0WQy19HzBnAawIrjAKXeo163VlaGUjTvLTENGEjnWAUVoIti02CYqIXL4RGR3MKylMjZZOK1Le0SvqjHff31Zon2FLeqammcreTe3+WhtOeEyqJiMAAAwF9b1jXlhDjjEiNXE6qJiuzIL0n8wKfmaFCZhiACx9pOviI5S7QGlu4p9MQ6V1y/sRDED8P49ngdxDCZcOjYEztyAoQHWok8sqGBI4xkAaKdFPyZZIRR7JasRWZaaH4LtYFF2HW6omwdmEKIiYJVfZqsuNJLB/TnE=
  on:
    tags: true
